# Generated by Django 3.2.8 on 2022-01-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('model_path', models.CharField(blank=True, max_length=512)),
                ('latest_prediction', models.CharField(blank=True, max_length=12)),
                ('latest_prediction_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
